services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enose
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: enose
      MQTT_BROKER: mqtt://mosquitto
      CSV_FILE: /app/data/sensor_data.csv
      JSON_FILE: /app/data/sensor_data.json
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data   # thư mục lưu file
    depends_on:
      - mosquitto
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
  
